### ISSUE TITLE
New theme

### ISSUE THREAD

**Issue by leejuyuu** [nomacs/nomacs.github.io#2]
I think we should go with an existing theme, get the site contents up, and think about customization later.

Here's what I am planning to try (in this order)
- https://github.com/aaranxu/adidoks
- https://github.com/codeandmedia/zola_easydocs_theme
- https://github.com/jakeswenson/zola-just-the-docs

Any other recommendations?

**Comment by mmahmoudian** [comment]
I personally was thinking of using [Seagull](https://www.getzola.org/themes/seagull/) theme as it is more closer to the old website's style. All those docs feel too text-based boring style. The audience Nomacs target are normal computer users rather than programmers who are trying to read about an API. That's why I think we need more color and style to make them feel realize Nomacs is not a old-fashioned outdated software.

Of course at the end it is all about design.

**Comment by leejuyuu** [comment]
I visited the Seagull demo and I still want to go with Adidoks. For Nomacs, the major visual elements on the website are screenshots. To make the app screenshots stand out, I feel that we can benefit from having a more simplistic template. Large background images are kind of weird for screenshots. Also, the Adidoks theme had performance, accessibility, and SEO considered, so it looks like a better default. As for making the site look modern and appealing, it's still very possible for us to make the landing page look great, judging from the many examples (from the original hugo theme) https://getdoks.org/showcase/.

**Comment by mmahmoudian** [comment]
Fair enough 👍 lets proceed with the theme of your choice and add the content. The rest can be modified, especially when we get feedback from other devs.

**Comment by leejuyuu** [comment]
Thanks! I'll leave this open and open a PR when I migrate the configs to the new theme.
