### ISSUE TITLE
Links directs to nomacs.org and reports 404

### ISSUE THREAD

**Issue by leejuyuu** [nomacs/nomacs.github.io#6]
Internal links points to `nomacs.org` and reports 404.

**Comment by mmahmoudian** [comment]
This a Github bug as far as I understand that removes the domain from the settings page. This is the first repo that I'm seeing this issue with though. Very peculiar. This is what I was trying to [explain before](https://github.com/nomacs/nomacs.github.io/pull/7#issuecomment-1939382460)

![image](https://github.com/nomacs/nomacs.github.io/assets/390889/0322f6f2-47cd-43ea-88c5-cafaf8bb4158)

When I add the domain it will look like this:

![image](https://github.com/nomacs/nomacs.github.io/assets/390889/bf5ecddd-e3c4-4352-8be0-44cc31f81845)

**Comment by leejuyuu** [comment]
You mean the input box for custom domain erases itself?

I still think it would be helpful changing base path to the actual host because that decouples the site from the custom domain.

**Comment by mmahmoudian** [comment]
> because that decouples the site from the custom domain.

but wasn't the whole point of this to keep the domain?

> You mean the input box for custom domain erases itself?

yes, and I think I know why. The CNAME file is in root folder but it should be moved to static. I will fix it in a PR

**Comment by leejuyuu** [comment]
Making `nomacs.github.io` self sufficient without the domain could make troubleshooting easier. We know immediately whether something is missing because it is not on the server and not because of some DNS/domain settings problems.

**Comment by mmahmoudian** [comment]
woops, sorry, I didn't mean to close this. It got closed automatically after merging

**Comment by mmahmoudian** [comment]
> Making nomacs.github.io self sufficient without the domain could make troubleshooting easier. We know immediately whether something is missing because it is not on the server and not because of some DNS/domain settings problems.

Yes, but it almost never is DNS problem if we keep using github pages. I have other projects on Github and it have been years since I touched their DNS records. I think now that we have the CNAME in correct place, everything should be automatically fine.

Also for two more reasons it would be beneficial to keep the domain:
1. it is part of the infrastructure (the Windows installs read the version file from a particular hard-coded URL)
2. Whenever this project decides to move away from Github,  Users will seamlessly migrate. 

Of course, I'm fine with the change. Perhaps we can ask @novomesk opinion as he is the lead dev as far as I know and his opinion worth more than mine :)

**Comment by leejuyuu** [comment]
I just found out that everything nomacs.github.io redirects to nomacs.org. If that is the case, and it works correctly now, I agree we should not change the base path to make the links and the domain consistent. I will close this issue and theassociated PR for now
